// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "eagleApiUrl": string;
      "eagleApiToken": string;
      "outputDirectory": string;
    };
  }
}
